spring:
  application:
    name: massmutual-spring-day2
  datasource:
    url: jdbc:h2:file:./data/productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          jdbc:
            time_zone: UTC
      open-in-view: false
    h2:
      console:
        enabled: true
        path: /h2-console

app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type,X-Requested-With"